[package]
name = "torrent-bot-server"
version = "1.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
torrent-bot-clients = { version = "1.1.0", path = "../torrent-bot-clients" }
