[package]
name = "torrent-bot-sniper"
version = "0.1.0"
edition = "2024"

[dependencies]
openai = { version = "1.1.0" }
serde = { version = "1.0.219" }
sled = { version = "0.34.7" }
thiserror = { version = "2.0.12" }
tracing = { version = "0.1.41" }
serde_json = { version = "1.0.140" }
